### ISSUE TITLE
uLTRA + SQANTI3

### ISSUE THREAD

**Issue by FJPardoPalacios** [ksahlin/ultra#7]
Hi Kristoffer,

I'm trying to implement uLTRA as a possible aligner for SQANTI3. I think you've already heard about SQANTI, but we've been working the last year and a half to release a much more complete software and it is [SQANTI3](https://github.com/ConesaLab/SQANTI3/), in case you want to have a look.

SQANTI3 was thought to evaluate transcriptomes as a GTF, but in some cases people ends up with a FASTA with all the sequences of their final transcripts (after some clustering, correction, polishing, etc) and they also want to evaluate it. SQANTI3 takes those sequences, map them and creates a GTF that can be evaluated easily. We have implemented GMAP, deSALT and minimpap2 (this is the default), but now I would like to include uLTRA too. 

What would your recommendation be for uLTRA parameters? Since sequences are, in theory, processed I was running it with `--isoseq` and `--ignore_rc` options, am I using them correctly?

Thanks!!
Fran

**Comment by ksahlin** [comment]
Hi Fran,

Since you mention that the reads usually are processed, I think `--isoseq` parameter is fine. However, please skip the `--ignore_rc` flag. This was an experimental parameter used in development. Looking through the codebase I'm actually unsure it has any effect. 

Another parameter is the number of cores/threads `--t`. Default is 3 and uLTRA's memory footprint grows with the number of cores, it may be good to set this to what SQANTI3 [uses](https://github.com/ConesaLab/SQANTI3/blob/master/sqanti3_qc.py#L2360).  

I'm not sure about the most common use case you see with SQANTI3 (e.g., isoseq or ONT, human/non-human, and the number of reads in the datasets), but that is what I could think about if you have to choose a fixed parameter setting for uLTRA.

I recently implemented an option `--use_NAM_seeds` there are some tradeoffs with this option - faster and smaller intermediate files, but can be more memory consuming/slightly less accurate. If you're interested, [see here](https://github.com/ksahlin/ultra#new-since-v004).

Glad that you want to try it out and happy to receive feedback if you get any!

Best,
Kristoffer

**Comment by FJPardoPalacios** [comment]
Thanks for your quick response and your advise! I will remove the `--ignore_rc` flag and set the `--t` parameter as you said. Regarding the `--use_NAM_seeds`, I read about this option, but I will keep it "off". The idea is to map transcript-models, so it shouldn't be a problem the amount of sequences. The reference transcriptome from mouse has ~140k transcripts, it would be crazy to have >5M transcripts...

I'll let you know any insight that we get of this. But I won't open an issue, but I'll contact you :)

Bests,
Fran
